<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y9wx8MgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y9wx8Mg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y9wx8Mg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'property' => ['privates', '.errored..service_locator.y9wx8Mg.App\\Entity\\Property', NULL, 'Cannot autowire service ".service_locator.y9wx8Mg": it references class "App\\Entity\\Property" but no such service exists.'],
            'propertyRepository' => ['privates', 'App\\Repository\\PropertyRepository', 'getPropertyRepositoryService', true],
        ], [
            'property' => 'App\\Entity\\Property',
            'propertyRepository' => 'App\\Repository\\PropertyRepository',
        ]);
    }
}
