<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U2PMc5JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u2PMc5J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u2PMc5J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'type' => ['privates', '.errored..service_locator.u2PMc5J.App\\Entity\\Type', NULL, 'Cannot autowire service ".service_locator.u2PMc5J": it references class "App\\Entity\\Type" but no such service exists.'],
            'typeRepository' => ['privates', 'App\\Repository\\TypeRepository', 'getTypeRepositoryService', true],
        ], [
            'type' => 'App\\Entity\\Type',
            'typeRepository' => 'App\\Repository\\TypeRepository',
        ]);
    }
}
