<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZU75XyYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zU75XyY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zU75XyY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'casesRepository' => ['privates', 'App\\Repository\\CasesRepository', 'getCasesRepositoryService', true],
            'player' => ['privates', '.errored..service_locator.zU75XyY.App\\Entity\\Player', NULL, 'Cannot autowire service ".service_locator.zU75XyY": it references class "App\\Entity\\Player" but no such service exists.'],
            'playerRepository' => ['privates', 'App\\Repository\\PlayerRepository', 'getPlayerRepositoryService', true],
        ], [
            'casesRepository' => 'App\\Repository\\CasesRepository',
            'player' => 'App\\Entity\\Player',
            'playerRepository' => 'App\\Repository\\PlayerRepository',
        ]);
    }
}
