<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YfIvB2gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YfIvB2g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YfIvB2g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'station' => ['privates', '.errored..service_locator.YfIvB2g.App\\Entity\\Station', NULL, 'Cannot autowire service ".service_locator.YfIvB2g": it references class "App\\Entity\\Station" but no such service exists.'],
        ], [
            'station' => 'App\\Entity\\Station',
        ]);
    }
}
