<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ccx1P9XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ccx1P9X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ccx1P9X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cases' => ['privates', '.errored..service_locator.Ccx1P9X.App\\Entity\\Cases', NULL, 'Cannot autowire service ".service_locator.Ccx1P9X": it references class "App\\Entity\\Cases" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'cases' => 'App\\Entity\\Cases',
            'doctrine' => '?',
        ]);
    }
}
