<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GH4jdibService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gH4jdib' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gH4jdib'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'luck' => ['privates', '.errored..service_locator.gH4jdib.App\\Entity\\Luck', NULL, 'Cannot autowire service ".service_locator.gH4jdib": it references class "App\\Entity\\Luck" but no such service exists.'],
            'luckRepository' => ['privates', 'App\\Repository\\LuckRepository', 'getLuckRepositoryService', true],
        ], [
            'luck' => 'App\\Entity\\Luck',
            'luckRepository' => 'App\\Repository\\LuckRepository',
        ]);
    }
}
