<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__RfT2MFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..rfT2MF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..rfT2MF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'casesRepository' => ['privates', 'App\\Repository\\CasesRepository', 'getCasesRepositoryService', true],
            'iconRepository' => ['privates', 'App\\Repository\\IconRepository', 'getIconRepositoryService', true],
            'playerRepository' => ['privates', 'App\\Repository\\PlayerRepository', 'getPlayerRepositoryService', true],
        ], [
            'casesRepository' => 'App\\Repository\\CasesRepository',
            'iconRepository' => 'App\\Repository\\IconRepository',
            'playerRepository' => 'App\\Repository\\PlayerRepository',
        ]);
    }
}
