<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IAA5CEeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IAA5CEe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IAA5CEe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'case' => ['privates', '.errored..service_locator.IAA5CEe.App\\Entity\\Cases', NULL, 'Cannot autowire service ".service_locator.IAA5CEe": it references class "App\\Entity\\Cases" but no such service exists.'],
        ], [
            'case' => 'App\\Entity\\Cases',
        ]);
    }
}
