<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCases2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BaCpOE4.App\Entity\Cases' shared service.
     *
     * @return \App\Entity\Cases
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BaCpOE4": it references class "App\\Entity\\Cases" but no such service exists.');
    }
}
