<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIcon2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zysq8RA.App\Entity\Icon' shared service.
     *
     * @return \App\Entity\Icon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zysq8RA": it references class "App\\Entity\\Icon" but no such service exists.');
    }
}
