<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLuck2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.utW0BxU.App\Entity\Luck' shared service.
     *
     * @return \App\Entity\Luck
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.utW0BxU": it references class "App\\Entity\\Luck" but no such service exists.');
    }
}
