<?php

namespace Container4JeVWHo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProperty2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.y9wx8Mg.App\Entity\Property' shared service.
     *
     * @return \App\Entity\Property
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.y9wx8Mg": it references class "App\\Entity\\Property" but no such service exists.');
    }
}
